#!/usr/bin/env bash
# Version: 1.2.1
#
# 1.2.1 (2026-08-30) — HermesAgentV5 consolidation: REPO_DIR default and the check-in
# prompt's `mediawiki.py` path repointed from HermesAgentV4 to HermesAgentV5.
#
# 1.2.0 — security-review follow-up: the room ID is now percent-encoded
# (jq's @uri) before being embedded in the Matrix API URL.
#
# 1.1.0 — the hermes-ops-ctl bearer token no longer transits curl's argv —
# was visible via `ps`/`/proc/<pid>/cmdline` for the life of the call.
# Moved to a `curl -K -` stdin config; verified live the header still sends
# correctly and the token no longer appears in the process's own argv.
#
# Real, external "wake up and consider wiki maintenance" trigger for a persona. Built after a
# real fabrication incident (2026-08-03, see LESSONS_LEARNED.md): asked for a Daily Blog page
# that "updates automatically," Sintra had no real tool that could create a cron job or systemd
# timer — she has no crontab or systemctl access at all, by design (per-identity isolation) — so
# she narrated having scheduled one instead of saying she couldn't. `sudo -u sintra crontab -l`
# and `systemctl list-timers` both confirmed nothing was ever actually created.
#
# Neither persona can create their own recurring automation, and that isn't changing. What can
# change is providing a real external trigger so "checking the wiki once a day" doesn't have to
# be something a persona invents. This script posts a genuine Matrix message into the persona's
# own home room — the same channel a person would use — so it flows through the gateway's normal
# inbound pipeline and produces a real, ordinary agent turn, not a special invocation path.
#
# Posted as @hermes-ops-ctl:spark (vault item matrix-ops-ctl), not the persona's own account: the
# gateway drops any event whose sender matches its own logged-in user_id before parsing reaches
# the model at all (plugins/platforms/matrix/adapter.py _is_self_sender, LESSONS_LEARNED.md §7),
# so a message "from itself" would never produce a turn. Same "never the persona" pattern already
# used for @fleetops:spark (render delivery) and the !new trigger in hermes-session-cap-guard.sh.
#
# Meant to be run by a pmoney-owned systemd timer, once daily, staggered per persona so both
# aren't reasoning at once — see infra/hermes-wiki-checkin/.
#
# Usage: hermes-wiki-checkin-trigger.sh <sintra|amy>
# Requires: tools/vault-get-secret.sh, jq, curl.
set -euo pipefail

REPO_DIR="${HERMES_REPO_DIR:-$HOME/HermesAgentV5}"
MATRIX_URL="${MATRIX_URL:-http://127.0.0.1:6167}"

NODE="${1:?usage: hermes-wiki-checkin-trigger.sh <sintra|amy>}"
case "$NODE" in
  sintra) HOME_ROOM="!teSvzXTJKwZyuh8QK8:spark" ;;
  amy)    HOME_ROOM="!KvSV6SCscjEO8QWjuP:spark" ;;
  *) echo "[wiki-checkin-trigger] Unknown node '$NODE' — no home room mapping" >&2; exit 1 ;;
esac
PERSONA_PAGE="$(printf '%s' "${NODE:0:1}" | tr '[:lower:]' '[:upper:]')${NODE:1}"

log() { echo "[wiki-checkin-trigger] $*" >&2; }

OPS_CTL_TOKEN="$("$REPO_DIR/tools/vault-get-secret.sh" matrix-ops-ctl password)"
if [ -z "$OPS_CTL_TOKEN" ]; then
  log "ERROR: could not fetch matrix-ops-ctl token, exiting"
  exit 1
fi

PROMPT="SYSTEM (wiki-checkin, automated, daily): this is your scheduled daily check-in for your own wiki space — a real external trigger, sent by a systemd timer outside your own control, not something you set up. Review what actually happened today that you have real evidence of (real tool calls, real jobs, real conversations) and decide whether it's worth a Daily Blog entry. If something real happened: python3 ~/HermesAgentV5/tools/mediawiki.py blog-entry \"${PERSONA_PAGE}/Daily-Blog\" --summary \"<why>\" --stdin — the date heading is generated by the tool itself, never write a date or a \$DATE placeholder yourself. If nothing notable happened, doing nothing is the correct outcome; do not invent an entry to fill the slot. And a hard rule regardless of what you write: you do not have crontab or systemctl access and cannot create scheduled automation yourself — never describe or claim a cron job, timer, or scheduled task as something you set up, on this page or anywhere else. This message is the only real mechanism behind any 'daily' or 'automatic' wiki behavior you have."

# Puts the Authorization header on stdin via curl -K instead of argv, so the
# live token is never visible via `ps`/`/proc/<pid>/cmdline` for the life of
# the call. Room ID percent-encoded (jq's @uri) for safe use in the URL path.
txn="wikicheckin-$(date +%s%N)"
ROOM_ID_ENC="$(jq -rn --arg s "$HOME_ROOM" '$s|@uri')"
resp="$(printf 'header = "Authorization: Bearer %s"\n' "$OPS_CTL_TOKEN" | \
  curl -sf -K - -X PUT "$MATRIX_URL/_matrix/client/v3/rooms/$ROOM_ID_ENC/send/m.room.message/$txn" \
  -H "Content-Type: application/json" \
  -d "$(jq -n --arg body "$PROMPT" '{msgtype: "m.text", body: $body}')")"

if [ -z "$resp" ] || ! echo "$resp" | jq -e '.event_id' >/dev/null 2>&1; then
  log "ERROR: post did not return an event_id: $resp"
  exit 1
fi
log "check-in prompt posted to $NODE's home room ($HOME_ROOM), event $(echo "$resp" | jq -r '.event_id')"
